# Generated by Django 6.0.1 on 2026-01-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': '1. Categorias'},
        ),
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name_plural': '4. Compras'},
        ),
        migrations.AlterModelOptions(
            name='despesa',
            options={'verbose_name_plural': '6. Despesas'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': '2. Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name_plural': '3. Produtos'},
        ),
        migrations.AlterModelOptions(
            name='receitaextra',
            options={'verbose_name_plural': '7. Receitas Extras'},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name_plural': '5. Vendas'},
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
