# Generated by Django 6.0.1 on 2026-01-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_categoria_options_alter_compra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('nome', 'marca')},
        ),
    ]
