# Generated by Django 6.0.1 on 2026-01-21 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_alter_produto_marca_alter_produto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Médio (Kz)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda (Kz)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='stock_actual',
            field=models.IntegerField(default=0, verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='stock_minimo',
            field=models.IntegerField(default=5, verbose_name='Stock Mínimo'),
        ),
    ]
