# Generated by Django 6.0.1 on 2026-02-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_alter_produto_categoria_alter_produto_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Preço de Custo (Kz)'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='metodo_pagamento',
            field=models.CharField(choices=[('DIN', 'Dinheiro'), ('TPA', 'TPA'), ('TRANS', 'Transferência')], max_length=10),
        ),
    ]
