# Generated by Django 6.0.1 on 2026-05-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_itemcompra_preco_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
